export class OcGenInfoInfo {
    quoteIdOc : number;
	openQuotationNo : string;
	lineCd : string;
	lineCdDesc : string;
	year : number;
	seqNo : number;
	revNo : number;
	cedingId : number;
	cessionId : number;
	cedingName : string;
	lineClassCd : string;
	lineClassDesc : string;
	refPolNo : string;
	policyIdOc : number;
	openPolicyNo : string;
	prinId : number;
	principalName : string;
	contractorId : number;
	contactorName : string;
	insuredDesc : string;
	status : string;
	reinsurerId : number;
	reinsurerName : string;
	intmId : number;
	intmName : string;
	issueDate : Date;
	expiryDate : Date;
	reqBy : string;
	reqDate : Date;
	reqMode : string;
	currencyCd : string;
	currencyRt : number;
	govtTag : string;
	indicativeTag : string;
	preparedBy : string;
	approvedBy : string;
	printedBy : string;
	printDate : Date;
	openingParag : string;
	closingParag : string;
	reasonCd : string;
	reasonDesc : string;
	createUser : string;
	createDate : string;
	updateUser : string;
    updateDate : Date;
    
	projId : number;
	projDesc : string;
	riskId : number;
	maxSi : number;
	pctShare : number;
	totalValue : number;
	objectId : number;
	site : string;
	duration : string;
	testing : string;
	createUserProj : string;
	createDateProj : Date
	updateUserProj : string;
	updateDateProj : Date;

   
    // constructor(quoteIdOc : number,openQuotationNo : string,lineCd : string,lineCdDesc : string,year : number,seqNo : number,revNo : number,cedingId : number,cessionId : number,cedingName : string,lineClassCd : string,lineClassDesc : string,refPolNo : string,policyIdOc : number,openPolicyNo : string,prinId : number,principalName : string,contractorId : number,contactorName : string,insuredDesc : string,status : string,reinsurerId : number,reinsurerName : string,intmId : number,intmName : string,issueDate : Date,expiryDate : Date,reqBy : string,reqDate : Date,reqMode : string,currencyCd : string,currencyRt : number,govtTag : string,indicativeTag : string,preparedBy : string,approvedBy : string,printedBy : string,printDate : Date,openingParag : string,closingParag : string,reasonCd : string,reasonDesc : string,createUser : string,createDate : Date,updateUser : string,updateDate : Date,        
    //     projId : number,projDesc : string,riskId : number,maxSi : number,pctShare : number,totalValue : number,objectId : number,site : string,duration : string,testing : string,createUserProj : string,createDateProj : Date,updateUserProj : string,updateDateProj : Date){

    // this.quoteIdOc  = quoteIdOc;
	// this.openQuotationNo    = openQuotationNo;
	// this.lineCd     = lineCd;
	// this.lineCdDesc     = lineCdDesc;
	// this.year   = year;
	// this.seqNo  = seqNo;
	// this.revNo  = revNo;
	// this.cedingId   = cedingId;
	// this.cessionId  = cessionId;
	// this.cedingName     = cedingName;
	// this.lineClassCd    = lineClassCd;
	// this.lineClassDesc  = lineClassDesc;
	// this.refPolNo   = refPolNo;
	// this.policyIdOc     = policyIdOc;
	// this.openPolicyNo   = openPolicyNo;
	// this.prinId     = prinId;
	// this.principalName  = principalName;
	// this.contractorId   = contractorId;
	// this.contactorName  = contactorName;
	// this.insuredDesc    = insuredDesc;
	// this.status     = status;
	// this.reinsurerId    = reinsurerId;
	// this.reinsurerName  = reinsurerName;
	// this.intmId     = intmId;
	// this.intmName   = intmName;
	// this.issueDate  = issueDate;
	// this.expiryDate     = expiryDate;
	// this.reqBy  = reqBy;
	// this.reqDate    = reqDate;
	// this.reqMode    = reqMode;
	// this.currencyCd     = currencyCd;
	// this.currencyRt     = currencyRt;
	// this.govtTag    = govtTag;
	// this.indicativeTag  = indicativeTag;
	// this.preparedBy     = preparedBy;
	// this.approvedBy     = approvedBy;
	// this.printedBy  = printedBy;
	// this.printDate  = printDate;
	// this.openingParag   = openingParag;
	// this.closingParag   = closingParag;
	// this.reasonCd   = reasonCd;
	// this.reasonDesc     = reasonDesc;
	// this.createUser     = createUser;
	// this.createDate     = createDate;
	// this.updateUser     = updateUser;
    // this.updateDate     = updateDate;
    
	// this.projId     = projId;
	// this.projDesc   = projDesc;
	// this.riskId     = riskId;
	// this.maxSi  = maxSi;
	// this.pctShare   = pctShare;
	// this.totalValue     = totalValue;
	// this.objectId   = objectId;
	// this.site   = site;
	// this.duration   = duration;
	// this.testing    = testing;
	// this.createUserProj     = createUserProj;
	// this.createDateProj     = createDateProj;
	// this.updateUserProj     = updateUserProj;
	// this.updateDateProj     = updateDateProj;
    // }
    
}